#version: "3.8"

services:
  pyroll_develop:
    build: 
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: pyroll_test_develop
    command: /start
    networks:
      - nginx_network
    volumes:
      - .:/code
      - static_volume:/code/app/static
      - media_volume:/code/app/images
      - logs:/code/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env.pyrollprod



  nginx_pyroll:
    container_name: pyroll_nginx_develop
    build: ./nginx
    ports:
      - "8011:8011"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/app/static
      - ./app/media:/code/app/media
      # - media_volume:/code/app/media
    restart: "on-failure"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  logs: