# Generated by Django 5.2.5 on 2025-08-21 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_rate', models.FloatField(null=True)),
                ('as_of_date', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_name', models.CharField(max_length=255)),
                ('formula_expression', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=122)),
                ('code', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField()),
                ('resign', models.BooleanField(default=False)),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='employee_images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('department_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups')),
                ('department_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.designation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.location')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.CharField(max_length=40)),
                ('fuel_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialImpactPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_years', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emp_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeestatus')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus', to='user.formula')),
                ('gratuity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gratuity', to='user.formula')),
                ('leave_encashment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='le', to='user.formula')),
                ('mobile_allowance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_allowance', to='user.formula')),
                ('total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total', to='user.formula')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.gender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='hr_assigned_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncrementDetailsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField(null=True)),
                ('eligible_for_increment', models.IntegerField(null=True)),
                ('current_salary', models.FloatField(null=True)),
                ('effective_increment_rate_hod', models.FloatField(null=True)),
                ('effective_fuel_percentage_hod', models.FloatField(null=True)),
                ('salary_increment_impact_hod', models.FloatField(null=True)),
                ('fuel_increment_impact_hod', models.FloatField(null=True)),
                ('other_costs_in_p_and_l', models.FloatField(null=True)),
                ('total_cost_on_p_and_l_per_month', models.FloatField(null=True)),
                ('revised_department_salary', models.FloatField(null=True)),
                ('staff_revised_cost', models.FloatField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('department_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedPackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('increased_fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
                ('increased_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increased_amount', to='user.formula')),
                ('revised_fuel_allowance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_fuel_allowance', to='user.formula')),
                ('revised_salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_salary', to='user.formula')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.section'),
        ),
    ]
