# Generated by Django 5.2.5 on 2025-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='mileage_km',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total distance travelled in kilometers', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('brand', 'model_name', 'year', 'condition')},
        ),
    ]
