# Generated by Django 5.2.5 on 2025-08-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalImpactPerMonth',
            new_name='FinancialImpactPerMonth',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_resignation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='resign',
            field=models.BooleanField(default=False),
        ),
    ]
