# Generated by Django 5.2.5 on 2025-08-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_finalimpactpermonth_financialimpactpermonth_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='DepartmentGroups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups'),
        ),
        migrations.AddField(
            model_name='section',
            name='department_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups'),
        ),
        migrations.CreateModel(
            name='DepartmentTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams'),
        ),
    ]
