# Generated by Django 5.2.5 on 2025-08-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_targetfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldformula',
            name='formula',
            field=models.ForeignKey(help_text='Formula to apply.', on_delete=django.db.models.deletion.CASCADE, to='user.formula'),
        ),
    ]
