# Generated by Django 5.2.5 on 2025-09-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_vehicle_allowance_currentpackagedetails_fuel_allowance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_admin_access', 'Can Admin Access'), ('can_hr_level_access', 'Can HR Level Access')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_time_login_to_reset_pass',
            field=models.BooleanField(default=True),
        ),
    ]
