# Generated by Django 5.2.5 on 2025-08-27 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_vehiclemodel_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='ownership_type',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='currentpackagedetails',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='proposedpackagedetails',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vehiclemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.CharField(default='cc', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VehicleOwnerShipModel',
        ),
        migrations.DeleteModel(
            name='VehicleInfo',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='year',
        ),
    ]
