# Generated by Django 5.2.5 on 2025-08-28 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_vehicleinfo_ownership_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDraft',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('resign', models.BooleanField(default=False, null=True)),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='employee_draft_images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_fields', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('department_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups')),
                ('department_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='user.employee')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.location')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.section')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPackageDetailsDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mobile_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_fields', models.JSONField(blank=True, default=dict)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vehiclemodel')),
                ('employee_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_package_drafts', to='user.employeedraft')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialImpactPerMonthDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_years', models.IntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gratuity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leave_encashment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mobile_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_fields', models.JSONField(blank=True, default=dict)),
                ('emp_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employeestatus')),
                ('employee_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_impact_drafts', to='user.employeedraft')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedPackageDetailsDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('increased_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revised_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('increased_fuel_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revised_fuel_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mobile_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_fields', models.JSONField(blank=True, default=dict)),
                ('employee_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_package_drafts', to='user.employeedraft')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vehiclemodel')),
            ],
        ),
    ]
