# Generated by Django 5.2.5 on 2025-08-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_department_departmentgroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_assigned_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncrementDetailsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField()),
                ('eligible_for_increment', models.IntegerField()),
                ('current_salary', models.FloatField()),
                ('effective_increment_rate_hod', models.FloatField()),
                ('salary_increment_impact_hod', models.FloatField()),
                ('fuel_increment_impact_hod', models.FloatField()),
                ('other_costs_in_p_and_l', models.FloatField()),
                ('total_cost_on_p_and_l_per_month', models.FloatField()),
                ('revised_department_salary', models.FloatField()),
                ('staff_revised_cost', models.FloatField()),
                ('department_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams')),
            ],
        ),
    ]
