# Generated by Django 5.2.5 on 2025-09-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fieldformula',
            name='employee_or_department_required',
        ),
        migrations.RemoveField(
            model_name='fieldformula',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='fieldformula',
            name='target_field',
        ),
        migrations.RemoveField(
            model_name='fieldformula',
            name='target_model',
        ),
        migrations.AddField(
            model_name='formula',
            name='target_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='target_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='fieldformula',
            constraint=models.CheckConstraint(condition=models.Q(('department_team__isnull', False)), name='department_required'),
        ),
    ]
