# Generated by Django 5.2.5 on 2025-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vehiclebrand_vehicleownershipmodel_vehiclemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
