# Generated by Django 5.2.5 on 2025-08-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_fieldformula_formula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetfield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fieldformula',
            name='target_fields',
        ),
        migrations.RemoveField(
            model_name='fieldformula',
            name='department_teams',
        ),
        migrations.RemoveField(
            model_name='fieldformula',
            name='employees',
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='department_team',
            field=models.ForeignKey(default=9, help_text='Required if no employee: Formula applies to this department team.', on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams'),
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Optional: Formula applies to this employee only.', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='target_field',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='target_model',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldformula',
            name='formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.formula'),
        ),
        migrations.AddConstraint(
            model_name='fieldformula',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department_team__isnull', False), ('employee__isnull', True)), ('employee__isnull', False), _connector='OR'), name='employee_or_department_required'),
        ),
        migrations.DeleteModel(
            name='TargetField',
        ),
    ]
