# Generated by Django 5.2.5 on 2025-08-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vehicleinfo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpackagedetails',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vehicleinfo'),
        ),
        migrations.AlterField(
            model_name='proposedpackagedetails',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vehicleinfo'),
        ),
    ]
