# Generated by Django 5.2.5 on 2025-09-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_fieldformula_employee_or_department_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='formula_is_default',
            field=models.BooleanField(default=False),
        ),
    ]
