# Generated by Django 5.2.5 on 2025-08-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hr_assigned_companies_incrementdetailssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_rate', models.FloatField(null=True)),
                ('as_of_date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='incrementdetailssummary',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AddField(
            model_name='incrementdetailssummary',
            name='effective_fuel_percentage_hod',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='current_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='effective_increment_rate_hod',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='eligible_for_increment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='fuel_increment_impact_hod',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='other_costs_in_p_and_l',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='revised_department_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='salary_increment_impact_hod',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='staff_revised_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='total_cost_on_p_and_l_per_month',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='total_employees',
            field=models.IntegerField(null=True),
        ),
    ]
