# Generated by Django 5.2.5 on 2025-08-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employeedraft_currentpackagedetailsdraft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialimpactpermonth',
            old_name='mobile_allowance',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='proposedpackagedetails',
            old_name='mobile_allowance',
            new_name='fuel_litre',
        ),
        migrations.RemoveField(
            model_name='currentpackagedetails',
            name='mobile_allowance',
        ),
        migrations.AddField(
            model_name='currentpackagedetails',
            name='fuel_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='currentpackagedetails',
            name='mobile_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentpackagedetails',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentpackagedetails',
            name='vehicle_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='eligible_for_increment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedpackagedetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedpackagedetails',
            name='mobile_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedpackagedetails',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposedpackagedetails',
            name='vehicle_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
