# Generated by Django 5.2.5 on 2025-08-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_configurations_rename_company_name_employee_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
