# Generated by Django 5.2.5 on 2025-08-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_mobile_allowance_financialimpactpermonth_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='promoted_from_intern_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
