# Generated by Django 5.2.5 on 2025-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_formula_formula_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='effective_fuel_percentage_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='effective_increment_rate_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='fuel_increment_impact_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='other_costs_in_p_and_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='revised_department_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='salary_increment_impact_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='staff_revised_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummary',
            name='total_cost_on_p_and_l_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='effective_fuel_percentage_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='effective_increment_rate_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='fuel_increment_impact_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='other_costs_in_p_and_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='revised_department_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='salary_increment_impact_hod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='staff_revised_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementdetailssummarydraft',
            name='total_cost_on_p_and_l_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
