# Generated by Django 5.2.5 on 2025-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_employee_is_intern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auto_mark_eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
