# Generated by Django 5.2.5 on 2025-09-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0006_alter_incrementdetailssummary_current_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=10)),
                ('inline_editable', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('department_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams')),
            ],
            options={
                'unique_together': {('company', 'department_team', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DynamicAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField(default='0')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dynamicattributedefinition')),
            ],
        ),
    ]
