# Generated by Django 5.2.5 on 2025-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_employee_auto_mark_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentpackagedetails',
            name='company_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedpackagedetails',
            name='company_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
