# Generated by Django 5.2.5 on 2025-10-03 12:24

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_dynamicattributedefinition_dynamicattribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dynamicattributedefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dynamicattributedefinition',
            name='field_reference',
            field=models.ForeignKey(default=user.models.default_field_reference, on_delete=django.db.models.deletion.DO_NOTHING, to='user.fieldreference'),
        ),
        migrations.RemoveField(
            model_name='dynamicattributedefinition',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='dynamicattributedefinition',
            name='key',
        ),
    ]
