# Generated by Django 5.2.5 on 2025-10-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_dynamicattributedefinition_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dynamicattributedefinition',
            unique_together={('company', 'department_team', 'field_reference')},
        ),
    ]
