# Generated by Django 5.2.5 on 2025-08-21 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_designation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
