# Generated by Django 5.2.5 on 2025-09-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_currentpackagedetails_company_pickup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentpackagedetailsdraft',
            old_name='mobile_allowance',
            new_name='fuel_litre',
        ),
        migrations.RenameField(
            model_name='financialimpactpermonthdraft',
            old_name='mobile_allowance',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='proposedpackagedetailsdraft',
            old_name='mobile_allowance',
            new_name='fuel_litre',
        ),
        migrations.AddField(
            model_name='currentpackagedetailsdraft',
            name='company_pickup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='currentpackagedetailsdraft',
            name='mobile_provided',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='currentpackagedetailsdraft',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentpackagedetailsdraft',
            name='vehicle_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeedraft',
            name='auto_mark_eligibility',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedraft',
            name='eligible_for_increment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeedraft',
            name='is_intern',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeedraft',
            name='promoted_from_intern_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedpackagedetailsdraft',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='proposedpackagedetailsdraft',
            name='company_pickup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='proposedpackagedetailsdraft',
            name='mobile_provided',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='proposedpackagedetailsdraft',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedpackagedetailsdraft',
            name='vehicle_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='department_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups'),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='department_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams'),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.designation'),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.location'),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.section'),
        ),
    ]
