# Generated by Django 5.2.5 on 2025-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_mobile_allowance_currentpackagedetailsdraft_fuel_litre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpackagedetails',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposedpackagedetails',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
