# Generated by Django 5.2.5 on 2025-10-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_dynamicattributedefinition_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicattribute',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
