# Generated by Django 5.2.5 on 2025-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_designation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpackagedetails',
            name='vehicle',
            field=models.CharField(max_length=40),
        ),
    ]
