# Generated by Django 5.2.5 on 2025-10-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_dynamicattribute_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialimpactpermonth',
            old_name='serving_years',
            new_name='serving_period',
        ),
        migrations.RenameField(
            model_name='financialimpactpermonthdraft',
            old_name='serving_years',
            new_name='serving_period',
        ),
    ]
