# Generated by Django 5.2.5 on 2025-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_serving_years_financialimpactpermonth_serving_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='report_to',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeedraft',
            name='report_to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
