# Generated by Django 5.2.5 on 2025-09-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_employee_emp_id_remove_employeedraft_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedraft',
            name='emp_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
