# Generated by Django 5.2.5 on 2025-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_employee_emp_id_employeedraft_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreference',
            name='model_name',
            field=models.CharField(choices=[('CurrentPackageDetails', 'Current Package Details'), ('ProposedPackageDetails', 'Proposed Package Details'), ('FinancialImpactPerMonth', 'Financial Impact Per Month'), ('IncrementDetailsSummary', 'Increment Details Summary'), ('Employee', 'Employee'), ('Configurations', 'Configurations')], max_length=255),
        ),
    ]
