# Generated by Django 5.2.5 on 2025-08-22 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_employee_department_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departmentgroups'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams'),
        ),
    ]
