# Generated by Django 5.2.5 on 2025-09-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_fieldreference_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreference',
            name='model_name',
            field=models.CharField(choices=[('CurrentPackageDetails', 'Current Package Details'), ('ProposedPackageDetails', 'Proposed Package Details'), ('FinancialImpactPerMonth', 'Financial Impact Per Month'), ('IncrementDetailsSummary', 'Increment Details Summary'), ('CurrentPackageDetailsDraft', 'Current Package Details Draft'), ('ProposedPackageDetailsDraft', 'Proposed Package Details Draft'), ('FinancialImpactPerMonthDraft', 'Financial Impact Per Month Draft'), ('IncrementDetailsSummaryDraft', 'Increment Details Summary Draft'), ('Employee', 'Employee'), ('Configurations', 'Configurations')], max_length=255),
        ),
        migrations.CreateModel(
            name='IncrementDetailsSummaryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField(null=True)),
                ('eligible_for_increment', models.IntegerField(null=True)),
                ('current_salary', models.FloatField(null=True)),
                ('effective_increment_rate_hod', models.FloatField(null=True)),
                ('effective_fuel_percentage_hod', models.FloatField(null=True)),
                ('salary_increment_impact_hod', models.FloatField(null=True)),
                ('fuel_increment_impact_hod', models.FloatField(null=True)),
                ('other_costs_in_p_and_l', models.FloatField(null=True)),
                ('total_cost_on_p_and_l_per_month', models.FloatField(null=True)),
                ('revised_department_salary', models.FloatField(null=True)),
                ('staff_revised_cost', models.FloatField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('department_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams')),
            ],
        ),
    ]
