# Generated by Django 5.2.5 on 2025-08-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_employee_department_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='related_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='related_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
