# Generated by Django 5.2.5 on 2025-09-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_fieldreference_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpackagedetailsdraft',
            name='employee_draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeedraft'),
        ),
    ]
