# Generated by Django 5.2.5 on 2025-09-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_currentpackagedetailsdraft_employee_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpackagedetailsdraft',
            name='employee_draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employeedraft'),
        ),
        migrations.AlterField(
            model_name='financialimpactpermonthdraft',
            name='employee_draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_impact_drafts', to='user.employeedraft'),
        ),
        migrations.AlterField(
            model_name='proposedpackagedetailsdraft',
            name='employee_draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_package_drafts', to='user.employeedraft'),
        ),
    ]
