# Generated by Django 5.2.5 on 2025-08-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_formula_related_field_formula_related_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='related_field',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='related_model',
        ),
    ]
