# Generated by Django 5.2.5 on 2025-09-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_currentpackagedetailsdraft_employee_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialimpactpermonthdraft',
            name='employee_draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employeedraft'),
        ),
        migrations.AlterField(
            model_name='proposedpackagedetailsdraft',
            name='employee_draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employeedraft'),
        ),
    ]
