# Generated by Django 5.2.5 on 2025-08-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_formula_related_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('model_name', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='FieldFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=255)),
                ('target_field', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.formula')),
            ],
            options={
                'unique_together': {('target_model', 'target_field')},
            },
        ),
    ]
