# Generated by Django 5.2.5 on 2025-09-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_financialimpactpermonthdraft_employee_draft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='vehicle_type',
            new_name='engine_cc',
        ),
    ]
