# Generated by Django 5.2.5 on 2025-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_vehicle_type_vehiclemodel_engine_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedpackagedetails',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='proposedpackagedetailsdraft',
            name='approved',
        ),
        migrations.AddField(
            model_name='incrementdetailssummary',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incrementdetailssummarydraft',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
