# Generated by Django 5.2.5 on 2025-08-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_fieldformula_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldformula',
            name='formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.formula'),
        ),
    ]
