# Generated by Django 5.2.5 on 2025-09-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_proposedpackagedetails_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('summary_submitted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='incrementdetailssummary',
            name='summaries_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.summarystatus'),
        ),
        migrations.AddField(
            model_name='incrementdetailssummarydraft',
            name='summaries_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.summarystatus'),
        ),
    ]
