# Generated by Django 5.2.5 on 2025-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_fieldformula_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreference',
            name='model_name',
            field=models.CharField(choices=[('CurrentPackageDetails', 'Current Package Details'), ('ProposedPackageDetails', 'Proposed Package Details'), ('FinancialImpactPerMonth', 'Financial Impact Per Month'), ('IncrementDetailsSummary', 'Increment Details Summary'), ('Employee', 'Employee')], max_length=255),
        ),
    ]
