# Generated by Django 5.2.5 on 2025-09-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_summarystatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentpackagedetails',
            old_name='vehicle_allowance',
            new_name='fuel_allowance',
        ),
        migrations.RenameField(
            model_name='currentpackagedetailsdraft',
            old_name='vehicle_allowance',
            new_name='fuel_allowance',
        ),
        migrations.RenameField(
            model_name='proposedpackagedetails',
            old_name='vehicle_allowance',
            new_name='increased_fuel_allowance',
        ),
        migrations.RenameField(
            model_name='proposedpackagedetails',
            old_name='fuel_litre',
            new_name='increased_fuel_litre',
        ),
        migrations.RenameField(
            model_name='proposedpackagedetailsdraft',
            old_name='fuel_litre',
            new_name='increased_fuel_allowance',
        ),
        migrations.RenameField(
            model_name='proposedpackagedetailsdraft',
            old_name='increased_fuel_amount',
            new_name='increased_fuel_litre',
        ),
        migrations.RemoveField(
            model_name='currentpackagedetails',
            name='fuel_limit',
        ),
        migrations.RemoveField(
            model_name='currentpackagedetailsdraft',
            name='fuel_limit',
        ),
        migrations.RemoveField(
            model_name='proposedpackagedetails',
            name='increased_fuel_amount',
        ),
        migrations.RemoveField(
            model_name='proposedpackagedetailsdraft',
            name='vehicle_allowance',
        ),
        migrations.AddField(
            model_name='configurations',
            name='bonus_constant_multiplier',
            field=models.FloatField(null=True),
        ),
    ]
