# Generated by Django 5.2.5 on 2025-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_financialimpactpermonth_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldformula',
            name='aggregate_type',
            field=models.CharField(blank=True, choices=[('sum', 'Sum'), ('avg', 'Average'), ('count', 'Count')], help_text='Aggregate type for fields from other models (e.g., sum, avg)', max_length=20),
        ),
    ]
