# Generated by Django 5.2.5 on 2025-08-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_fieldformula_aggregate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldformula',
            name='aggregate_type',
        ),
    ]
