# Generated by Django 5.2.5 on 2025-08-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_fieldformula_aggregate_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldformula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='department_team',
            field=models.ForeignKey(default=9, help_text='Required if no employee: Formula applies to this department team.', on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams'),
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Optional: Formula applies to this employee only.', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
        migrations.AddConstraint(
            model_name='fieldformula',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department_team__isnull', False), ('employee__isnull', True)), models.Q(('department_team__isnull', True), ('employee__isnull', False)), models.Q(('department_team__isnull', False), ('employee__isnull', False)), _connector='OR'), name='employee_or_department_required'),
        ),
    ]
