# Generated by Django 5.2.5 on 2025-08-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_fieldformula_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldformula',
            name='department_team',
            field=models.ForeignKey(help_text='Required if no employee: Formula applies to this department team.', on_delete=django.db.models.deletion.CASCADE, to='user.departmentteams'),
        ),
    ]
