# Generated by Django 5.2.5 on 2025-08-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_fieldformula_department_team'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fieldformula',
            name='employee_or_department_required',
        ),
        migrations.AddField(
            model_name='fieldformula',
            name='company',
            field=models.ForeignKey(default=1, help_text='Required: Formula applies to this company.', on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AddConstraint(
            model_name='fieldformula',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department_team__isnull', False), ('employee__isnull', True)), ('employee__isnull', False), _connector='OR'), name='employee_or_department_required'),
        ),
    ]
