# Generated by Django 5.2.5 on 2025-08-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_fieldformula_employee_or_department_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldformula',
            name='company',
            field=models.ForeignKey(help_text='Required: Formula applies to this company.', on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
